### ISSUE TITLE
Types for Linked Elements

### ISSUE THREAD

**Issue by furmandev** [kontent-ai/model-generator-js#21]
Is there any way to generate types for linked elements? (when the linked elements are restricted to a certain type or types).
Currently we are doing:

```ts
Movie.elements.stars.linkedItems as Actor[]
```

I think maybe what we would like is for the generated model to look like:

```ts
export type Movie = IContentItem<{
  stars: Elements.LinkedItemsElement<Actor>;
}>;
```

**Comment by Enngage** [comment]
Hey @furmandev,

This has been implemented in the latest version ;)
