### ISSUE TITLE
Abstract Content Type Snippets

### ISSUE THREAD

**Issue by WoodyWoodsta** [kontent-ai/model-generator-js#25]
### Motivation

At the moment, content type snippets are just flattened into the model types. This defeats the purpose of the single point of truth provided by the snippet functionality, and it would make obvious sense to generate separate types for the content snippets, and have the model types extend from them.

### Proposed solution

See above.

P.S. perhaps I've missed this functionality?

**Comment by WoodyWoodsta** [comment]
Apologies, I did not catch this closed issue: #24

**Comment by WoodyWoodsta** [comment]
In fact, I'll re-open it again, as even though content-type snippets are generated, they are not abstracted as above :)

**Comment by Enngage** [comment]
@WoodyWoodsta I've split the content type snippets and will release it soon :-) Thanks for the idea! If you can test it and let me know if that works for you, that would be great.

**Comment by WoodyWoodsta** [comment]
@Enngage Unfortunately I'm no longer working with Kontent, so will not be able to test.
