### ISSUE TITLE
Output dir option

### ISSUE THREAD

**Issue by WoodyWoodsta** [kontent-ai/model-generator-js#26]
### Motivation

At the moment, the generator simply outputs the files around the CWD. This is probably not as much of a problem for CLI users (although in any automated workflow, this is going to make everyone's life a bit harder), but it's not so great for programatic use. At the moment, I have a workspace project which generates the types programatically. The generator outputs the files around the root of this workspace, which muddies the project. I have to run a script to move the files to where I actually want them to be, which is in my main project.

### Proposed solution

Provide an `outputDir` option.

**Comment by vincent-aviva** [comment]
@WoodyWoodsta There is a workaround for this.
You can use the contentTypeFileResolver and assign a function to this.
In this way you can make it generate to a separate folder.
