### ISSUE TITLE
Add Subpages to generated page and homepage models

### ISSUE THREAD

**Issue by macdermott** [kontent-ai/model-generator-js#27]
### Motivation
Generated models for pages and the homepage do not explicitly reference subpages

### Proposed solution
Subpages of a model can be accessed via model.subpages

### Additional context
I know that subpages can currently be accessed via linkedItems, but explicitly separating out subpages helps when trying to build a hierarchical structure in a site generator

**Comment by Enngage** [comment]
@macdermott,

Thank you for the issue! If I understand it correctly, you are proposing a change of the actual underlying model defined by the `Delivery SDK` (https://github.com/kontent-ai/delivery-sdk-js) which would 'separate' subpages elements from the 'elements' section to its own property?

**Comment by macdermott** [comment]
Yes, that is correct. Ideally the models generated would separate out elements and subpages and the delivery SDK would be modified accordingly

**Comment by Freekbron** [comment]
I've got the same issue. I don't think the delivery SDK needs modification. It would make sense when subpages are part of the model under elements. 

My Homepage 'Content model' has:
- Title
- Subpages (web spotlight)
- Content

The generated file: `export type Homepage = IContentItem` only has:
- Title
- Content

**Comment by Enngage** [comment]
I've added the support for `subpages` element to the generator and released it under `5.4.0`. 

We are not planning on modifying the Delivery model to separate the subpages elements completely as it would bring inconsistency between other SDKs and elements. It should be fairly easy to programmatically find the subpages element by filtering based on the type.

**Comment by Freekbron** [comment]
Hi @Enngage, thanks for the quick response! 

Now I get the following error:
```
Cannot find name 'AlgemenePagina'.
 * Codename: subpages
 */
subpages: Elements.LinkedItemsElement<**Page**>;
```

It seems like the types in `subpages` (eg 'Page') are not imported as modules.

**Comment by Enngage** [comment]
@Freekbron, oh, you're right, sorry :) I've released a fix for that.

**Comment by Freekbron** [comment]
@Enngage Thanks, all working now!
