### ISSUE TITLE
Add const assertion to objects generated in the 'project' folder ( assetFolders.ts, collections.ts, contentTypes.ts, etc )

### ISSUE THREAD

**Issue by bzs-ngraham** [kontent-ai/model-generator-js#31]
### Motivation

To increase type-safety and minimize errors when querying for content items by their codename. 

Adding the const assertion will allow us to further constrain the codenames of content items by letting us know that the `codename` property is not just any string, but instead a very specific string.

### Proposed solution

The most simple solution would be to add `as const` to the end of the generated `contentTypes` object. For example:

```typescript
export const contentTypes = {
  /**
   * Homepage
   */
  homepage: {
    codename: 'homepage',
    id: '<guid>',
    externalId: undefined,
    name: 'Homepage',
    elements: {
      // ... elements here
    },
  },
} as const; // added
```

A quick example of how this changes type safety:

BEFORE:
![image](https://user-images.githubusercontent.com/93939495/191292493-034a891d-41a0-4199-b988-5d6cf0ca040f.png)

AFTER:
![image](https://user-images.githubusercontent.com/93939495/191292631-f0d7c7ea-0c60-4d72-baae-ce2966de4bb3.png)

### Additional context

TypeScript docs:
[https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions)

**Comment by Enngage** [comment]
Hi @bzs-ngraham,

Thank you for the idea! 

I'll test this (probably next week) and see how it works exactly. If all goes well, I will publish a new version with this ;)
