### ISSUE TITLE
Ability to turn off timestamps/metadata in Models

### ISSUE THREAD

**Issue by tomasvorel2** [kontent-ai/model-generator-js#35]
### Motivation
In our day-to-day workflow, we need to regenerate our models quite often. What is a bit annoying though is that we get a lot of unwanted diffs in our version control due to `Last modified:` time differences. For our purposes, we'd love to have the ability to turn this off so that our PRs are cleaner and we don't have to manually filter them as much.

### Proposed solution
Make the `Last modified` model property (or maybe even all metadata) optional

### Additional context
This is what we want to get rid of:
![model_generator_diff](https://user-images.githubusercontent.com/94854817/208620731-2d70177c-e217-4e74-b360-b3a87734ccb3.png)

**Comment by Enngage** [comment]
Hi,

There is already a `addTimestamp` setting that you can use for this purpose. Have a look at the readme, there are bunch of examples with this property.

**Comment by tomasvorel2** [comment]
Hi @Enngage ,

We have it set to `false` in our project so I'm not sure this is related.

**Comment by Enngage** [comment]
I see, this is different to the timestamp of when model generator runs... This is the timestamp of when your model was changed. I guess it might make sense to use the `addTimestamp` here as well.

**Comment by Enngage** [comment]
@tomasvorel2 I've released an update without the `last modified` information. I guess it's not that much useful information and it would probably cause more trouble for other users using source control as well.
