### ISSUE TITLE
Use Environment ID instead of Project ID

### ISSUE THREAD

**Issue by jancerman** [kontent-ai/model-generator-js#38]
### Brief bug description

The app uses and asks for project ID instead of environment ID. Based on recent product updates, users should provide their environment ID.

More context in [[CTC-1936] Use Environment ID instead of Project ID - Kontent.ai Jira](https://kontent-ai.atlassian.net/browse/CTC-1936).

### Expected behavior

Name parameters in a way so the users know to input their environment IDs.

**Comment by Enngage** [comment]
Done
