### ISSUE TITLE
Mac Error: Parse Error: Expected HTTP/

### ISSUE THREAD

**Issue by ookadoo** [kontent-ai/model-generator-js#41]
### Brief bug description

I attempt to generate models on a Mac yet receive and error.  When I try the same command on a PC, it works.

### Repro steps

1. Use a Mac
2. Attempt to generate typescript models
3. Observe error

### Expected behavior

Models generate without error

### Test environment

 - Platform/OS: Mac OS 12 or 13 (retried after upgrade, still failed)

### Additional context

The same command works on Windows.  Here are the parameters I use:

`npx @kontent-ai/model-generator --projectId=xxx --moduleResolution=ES2015 --codeType=TypeScript --strictPropertyInitialization=true --environmentId=xxx --apiKey=xxx`

**Comment by Enngage** [comment]
Hi @ookadoo,

It would be nice if you included the error message. I don't have access to Mac, but my colleagues are using this library on their Macs so I suppose it works ok. Also read through this thread as it may be related (also a note from my colleague running on Mac OS - [Iva_Bozic@epam.com](https://github.com/kontent-ai/model-generator-js/issues/10#issuecomment-1381918472))
