### ISSUE TITLE
Add option to skip file preamble generation

### ISSUE THREAD

**Issue by Simply007** [kontent-ai/model-generator-js#43]
### Motivation

For developing purposes, or testing ones, we ofte cline the project/create new environment.

Then we intrduce the new feature, but then you don'T get the full list of changed models, but a list of all models, where the preabmle is changed.

![image](https://github.com/kontent-ai/model-generator-js/assets/9218736/ab348ea3-a4ea-4105-baec-39e3be9532bf)

> disregard the older version, we have tweaked a thing or two to be able to run against the QA.

### Proposed solution

Add the new configuration next to `addTimestamp` that would allow to dissable generating the preable.

### Additional context

Stumble upon this issue - DEVREL-930

**Comment by Enngage** [comment]
@Simply007 I've added new option `addEnvironmentInfo` which does what you requested ;) It's released in `6.4.0`
