### ISSUE TITLE
Cannot generate a model for new subscription

### ISSUE THREAD

**Issue by TobiasVondracek** [kontent-ai/model-generator-js#51]
### Brief bug description

Cannot finish model generation due to invalid path /v2/projects/78a0b91a-c94a-009e-cc2b-f7d99eefa397/webhooks

### Repro steps

1. Create new subsription
2. Run this tool
3.       request: {
      ...
     path: '/v2/projects/78a0b91a-c94a-009e-cc2b-f7d99eefa397/webhooks',
      ...
    }data: {
      message: 'No HTTP resource was found that matches the request. See valid routes in API documentation at https://kontent.ai/learn/reference.'
    }

### Expected behavior

What is the correct behavior?

### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS]

### Screenshots

Add links to screenshots, if possible.

**Comment by IvanKiral** [comment]
Thanks @TobiasVondracek, 

we will look at it.

**Comment by IvanKiral** [comment]
The webhook endpoint is fixed by updating to new Management SDK :)

**Comment by Enngage** [comment]
Closing as done ;)
