### ISSUE TITLE
Fix workflow test job

### ISSUE THREAD

**Issue by IvanKiral** [kontent-ai/model-generator-js#54]
### Brief bug description

It seems that the github actions are not testing anything, but it still passes
<img width="1328" alt="image" src="https://github.com/kontent-ai/model-generator-js/assets/54802833/aaf4984f-b551-4f82-ae48-c0b4d0cd2def">

### Repro steps

1. Check any run that logs has not expired in Github
2. Click on test:all step
3. See error

### Expected behavior

The steps should be deleted or changed to the actual steps that tests something - right now it gives a fake impression that everything is working fine.

**Comment by Enngage** [comment]
I've slightly updated the workflow only to test lint & build since there are no tests ATM. Once we have some tests, they will be part of the `test:all` script ;)
