### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by IvanKiral** [kontent-ai/model-generator-js#56]
### Motivation

Currently, the supported node is according to the package.json >=. which is not correct as there is already used for example `replaceAll` in the codebase that is only supported in node 18. Let's get back to 2024 change supported engine to >= 18

### Proposed solution

Change engine to >= 18.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by Enngage** [comment]
Node is now set to `>= 18`, cheers! It was set via greater refactoring in https://github.com/kontent-ai/model-generator-js/commit/29dfa391b901c230b0de2797873b79339ef1fd1e
