### ISSUE TITLE
Names of content model that contain chars like emojis or em dash results in error

### ISSUE THREAD

**Issue by IvanKiral** [kontent-ai/model-generator-js#57]
### Brief bug description

Getting started project contains content types with em dash (—). Similar case is sample-project for fictohealthtech. generating models for this project results in error

### Expected behavior

It should generate the model with changed invalid characters

### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS]

### Screenshots

Add links to screenshots, if possible.

**Comment by Enngage** [comment]
Issues with emoticons and other special chars have been resolved in the upcoming update.
