### ISSUE TITLE
Model Generation fails with `SyntaxError: Invalid character.`

### ISSUE THREAD

**Issue by Nickm615** [kontent-ai/model-generator-js#59]
### Brief bug description

Model Generation fails with `SyntaxError: Invalid character.`
No more specific error message than that, but I've attached the full stack trace
[generator_stack_trace.txt](https://github.com/kontent-ai/model-generator-js/files/14937569/generator_stack_trace.txt)

### Repro steps

Run kontent-generate --environmentId=xxx --apiKey=xxx (I can provide these values for testing via direct message)

### Expected behavior

The models are successfully generated or if there is an issue a descriptive error message is displayed in the console.

### Test environment

Node v18.16.0
model-generator v 6.5.1

### Additional context
[Intercom Conversation](https://app.intercom.com/a/inbox/e42kus8l/inbox/admin/5497789/conversation/19590600535594?view=List)
We've checked the type that the process fails on for invalid characters in its name or elements but haven't found any. We also checked the MAPI validation endpoint but all of the returned issues are with variants rather than types.

### Screenshots

![image](https://github.com/kontent-ai/model-generator-js/assets/86981780/7eeffeb3-c472-410b-a516-9e8d3abd7000)

**Comment by Enngage** [comment]
Fixed and released in `7.0.2`
